=== zaineb88/TDI2/MOUSTAID/XML/exercice TD/exercice6/doc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT doc (title?, author?, chapter+)>
<!ELEMENT chapter (title, (para|note)*, section*)>
<!ELEMENT section (title, (para|note)*)>
<!ELEMENT title (#PCDATA|emph)*>
<!ELEMENT author (#PCDATA)>
<!ELEMENT para (#PCDATA|emph)*>
<!ELEMENT note (#PCDATA|emph)*>
<!ELEMENT emph (#PCDATA|emph)*>
<!ATTLIST chapter
num ID #REQUIRED
visible (true | false) "true">

=== zaineb88/TDI2/MOUSTAID/XML/exercice TD/exercice6/exercice6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc>
    <chapter num="ch1">
        <title>Chapter Title</title>
        <section>
            <title>Section Title</title>
            <note>This is a note.</note>
            <para>This is a test.</para>
            <para>This is <emph>another</emph> test.</para>
            <para>This is <emph>another</emph> test.</para>
            <para>This is <emph>another</emph> test.
                This is <emph>another</emph> test.
                This is <emph>another</emph> test.</para>
            <note>This is a note.</note>
        </section>
    </chapter>
    <chapter num="ch2" visible= "false">
        <title>Appendix</title>
    </chapter>
</doc>
