=== zaineb88/TDI2/MOUSTAID/XML/Dossier3-TDI-Ju2013-EFF-Th/Sans titre2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT stagiers (cours_du_soir?,Cours_du_jour,formatiom_qualificatiom?)>
<!ELEMENT cours_du_soir (filiere*)>
<!ELEMENT filiere (employee+)>
        <!ATTLIST filiere Nom  ID #REQUIRED  
           NombrePersonne CDATA  #IMPLIED>   
<!ELEMENT employee (societe,matricule,dateDubet,grade)>
<!ELEMENT societe (#PCDATA)>
<!ELEMENT matricule (#PCDATA)>
<!ELEMENT dateDubet (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT Cours_du_jour (filieres)>
<!ELEMENT filieres (stagier+,stagier+)>
         <!ATTLIST filieres Nom  ID #IMPLIED  
           NombrePersonne CDATA  #IMPLIED> 
<!ELEMENT stagier (n_insription,nom,prenom,age)>
<!ELEMENT n_insription (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT formatiom_qualificatiom (formatiom)>
<!ELEMENT formatiom (participant)>
<!ELEMENT participant (nome,tel)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT tel (#PCDATA)>

=== zaineb88/TDI2/MOUSTAID/XML/Dossier3-TDI-Ju2013-EFF-Th/Filiere.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stagiers SYSTEM "Sans titre2.dtd">
<stagiers>
    <cours_du_soir>
        <filiere  Nom="cccc"  NombrePersonne="4">
            <employee>
                <societe>SSTI</societe>
                <matricule>ER6530J</matricule>
                <dateDubet>2015-2-5</dateDubet>
                <grade>44566</grade>
            </employee>
        </filiere>      
    </cours_du_soir>
    <Cours_du_jour>
        <filieres  Nom="jjjjjj"  NombrePersonne="23">
            <stagier>
                <n_insription>5</n_insription>
                <nom>Tariaf</nom>
                <prenom>Aouatif</prenom>
                <age>21</age>
            </stagier>
            <stagier>
                <n_insription>5</n_insription>
                <nom>Tariaf</nom>
                <prenom>Aouatif</prenom>
                <age>21</age>
            </stagier>

            
        </filieres>
    </Cours_du_jour>
    <formatiom_qualificatiom>
        <formatiom >
            <participant>
                <nome>ffffffffff</nome>
                <tel>0699665544</tel>
            </participant>
            
        </formatiom>
    </formatiom_qualificatiom>
    
</stagiers>
