=== zaineb88/TDI2/MOUSTAID/XML/exercice TD/Exercice11/Sans titre6.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT LesArticles (Articles)+ >
<!ELEMENT  Articles (titre,contenu, bibliographie)>
<!ELEMENT  contenu (paragraphes,paragraphes)+>
<!ELEMENT  paragraphes ((mots+,expressions+),références+)>
<!ELEMENT bibliographie (siteweb|ouvrage) >
<!ELEMENT siteweb (nom,adressedesite) >
<!ELEMENT ouvrage (titreO,auteurs,datedeparution,éditeur)>
<!ELEMENT  titre  (#PCDATA) >
<!ELEMENT  mots  (#PCDATA) >
<!ELEMENT  expressions  (#PCDATA) >
<!ELEMENT  références  (#PCDATA) >
<!ELEMENT  nom  (#PCDATA) >
<!ELEMENT  adressedesite  (#PCDATA) >
<!ELEMENT  titreO  (#PCDATA) >
<!ELEMENT  auteurs  (#PCDATA) >
<!ELEMENT  datedeparution  (#PCDATA) >
<!ELEMENT  éditeur  (#PCDATA) >

=== zaineb88/TDI2/MOUSTAID/XML/exercice TD/exercice10/Sans titre9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Articles SYSTEM "Sans titre6.dtd">
<Articles>
    <titre>gg</titre>
    <contenu>
        <paragraphes>
            <mots>uytu</mots>
            <expressions>tytyu</expressions>
            <références>tyutyu</références>
        </paragraphes>
        <paragraphes>
            <mots>ytutyu</mots>
            <références>dgjhgd</références>
        </paragraphes>
        <paragraphes>
            <expressions>ghdjghdj</expressions>
            <références>ghdjy</références>
        </paragraphes>
    </contenu>
    <bibliographie>
        <siteweb>
            <nom>z'(truy</nom>
            <adressedesite>utyu</adressedesite>
        </siteweb>
        <ouvrage>
            <titreO>"''(yèrty</titreO>
            <auteurs>ayrtuy</auteurs>
            <datedeparution>tyeutyu</datedeparution>
            <éditeur>zryrtu</éditeur>
        </ouvrage>
    </bibliographie>
</Articles>

=== zaineb88/TDI2/MOUSTAID/XML/exercice TD/Exercice11/Sans titre9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LesArticles SYSTEM "Sans titre6.dtd">
<LesArticles>
    <Articles>
        <titre>mmmm</titre>
        <contenu>
            <paragraphes>
                <mots>aaaa</mots>
                <expressions>zzzz</expressions>
                <références>eeee</références>
            </paragraphes>
            <paragraphes>
                <mots>rrrrr</mots>
                <expressions>ttttttt</expressions>
                <références>yyyyyy</références>
            </paragraphes>         
        </contenu>
        <bibliographie>
            <siteweb>
                <nom>ooooo</nom>
                <adressedesite>eeeeeee</adressedesite>
            </siteweb>
        </bibliographie>
    </Articles>
</LesArticles>
